[package]
name = "jade-garden"
version.workspace = true
edition.workspace = true

[dependencies]
ember-core.workspace = true
ember-stdlib.workspace = true
macroquad.workspace = true
glam.workspace = true
serde.workspace = true
ron.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
soloud = "1.1"
dotenvy.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }

[dev-dependencies]
pollster = "0.4"

[lib]
name = "jade_garden"
path = "src/lib.rs"

[[bin]]
name = "jade-garden"
path = "src/main.rs"